
// This file contains the legal documents that are displayed in the plugin.
// You can customize the content of these documents to fit your needs.

const envs = {
    contactEmail: process.env.CONTACT_EMAIL,
    pluginName: process.env.PLUGIN_NAME,
    companyName: "Your Company Name",
    jurisdiction: "USA",
    mailingAddress: "123 Main Street, Anytown, USA",
}


export const legal = {
    name: 'Terms-Of-Service',
    description: `
    <!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Terms of Service for ${envs.pluginName}</title>
</head>

<body>
    <h1>Terms of Service for ${envs.pluginName}</h1>
    <p>Last Updated: March 23, 2023</p>
    <p>Welcome to the Terms of Service ("Terms") for ${envs.pluginName} ("Plugin"). These Terms are a legal agreement between
        you ("you," "your," or "user") and ${envs.companyName} ("we," "us," or "our") and govern your use of the Plugin. By
        using the Plugin, you agree to be bound by these Terms.</p>
    <h2>1. Usage Policies</h2>
    <p>We want everyone to use our Plugin safely and responsibly. By using the Plugin, you agree to comply with OpenAI's
        usage policies, which apply to all users of OpenAI's models, tools, and services. These usage policies outline
        disallowed uses of OpenAI's models, including but not limited to illegal activity, generation of hateful
        content, and activity that violates people's privacy. Please review OpenAI's usage policies carefully to
        understand the restrictions on using the Plugin.</p>
    <h2>2. Compliance with Policies</h2>
    <p>If we discover that your use of the Plugin does not comply with OpenAI's usage policies, we may ask you to make
        necessary changes. Repeated or serious violations may result in further action, including suspending or
        terminating your access to the Plugin. We reserve the right to modify our usage policies at any time, and it is
        your responsibility to review them periodically for changes.</p>
    <h2>3. Plugin Policies</h2>
    <p>In addition to OpenAI's usage policies, the following additional requirements apply to the use of the Plugin:</p>
    <ul>
        <li>a. The plugin manifest must have a clearly stated description that matches the functionality of the API
            exposed to the model.</li>
        <li>b. Don’t include irrelevant, unnecessary, or deceptive terms or instructions in the plugin manifest, OpenAPI
            endpoint descriptions, or plugin response messages.</li>
        <li>c. Don’t use the Plugin to circumvent or interfere with OpenAI’s safety systems.</li>
        <li>d. Don’t use the Plugin to automate conversations with real people, whether by simulating a human-like
            response or by replying with pre-programmed messages.</li>
        <li>e. Plugins that distribute personal communications or content generated by ChatGPT must indicate that the
            content was AI-generated.</li>
    </ul>
    <h2>4. Intellectual Property</h2>
    <p>All intellectual property rights in the Plugin, including but not limited to copyrights, trademarks, and trade
        secrets, are owned by us or our licensors. Your use of the Plugin does not grant you any ownership rights in the
        Plugin or its content.</p>
    <h2>5. Disclaimer of Warranties</h2>
    <p>The Plugin is provided "AS IS" and without warranties of any kind, whether express or implied. We do not warrant
        that the Plugin will meet your requirements, that its operation will be uninterrupted or error-free, or that the
        content generated by the Plugin will be accurate or reliable.</p>
    <h2>6. Limitation of Liability</h2>
    <p>To the fullest extent permitted by law, we shall not be liable for any direct, indirect, incidental, special,
        consequential, or exemplary damages arising out of or in connection with your use of the Plugin, even if we have
        been advised of the possibility of such damages.</p>
    <h2>7. Indemnification</h2>
    <p>You agree to indemnify, defend, and hold harmless us and our affiliates, officers, directors, employees, and
        agents from and against any and all claims, liabilities, damages, losses, and expenses, including reasonable
        attorneys' fees, arising out of or in connection with your use of the Plugin or your violation of these Terms.
    </p>
    <h2>8. Governing Law</h2>
    <p>These Terms shall be governed by and construed in accordance with the laws of ${envs.jurisdiction}, without regard to
        its conflict of law principles.</p>
    <h2>9. Changes to Terms</h2>
    <p>We reserve the right to modify these Terms at any time. Any changes to these Terms will be posted on this page,
        and your continued use of the Plugin after such changes have been posted constitutes your acceptance of the
        revised Terms.</p>
    <h2>10. Contact Information</h2>
    <p>If you have any questions or concerns about these Terms or the Plugin, please contact us at [Contact Email] or
        ${envs.mailingAddress}.</p>
    <h2>11. Entire Agreement</h2>
    <p>These Terms, together with any other agreements or policies referenced herein, constitute the entire agreement
        between you and us regarding the Plugin and supersede all prior or contemporaneous communications, agreements,
        or understandings, whether written or oral, relating to the Plugin.</p>
    <h2>12. Severability</h2>
    <p>If any provision of these Terms is found to be invalid or unenforceable by a court of competent jurisdiction, the
        remaining provisions of these Terms will remain in full force and effect, and the invalid or unenforceable
        provision will be deemed modified to the extent necessary to make it valid and enforceable.</p>
    <h2>13. No Waiver</h2>
    <p>No waiver of any provision of these Terms shall be effective unless it is in writing and signed by us. Our
        failure to enforce any provision of these Terms shall not be construed as a waiver of such provision or any
        other provision of these Terms.</p>
    <h2>14. Termination</h2>
    <p>We reserve the right, in our sole discretion, to terminate your access to the Plugin at any time, without notice,
        for any reason, including but not limited to your violation of these Terms or OpenAI's usage policies.</p>
    <p>By using the Plugin, you acknowledge that you have read, understood, and agree to be bound by these Terms.</p>
    <p>${envs.companyName}</p>
    <p>[Note: The above Terms of Service are provided as a template and should be customized to fit the specific
        circumstances of the Plugin and the company offering it. Additionally, it is recommended to seek legal advice
        when drafting or customizing legal documents such as Terms of Service.]</p>

</body>

</html>
    
    `,

};